name: Build and Compile APK
"on":
  push:
    branches:
      - master
      - termux-experimental

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: sdAI-release.apk
          path: app/build/outputs/apk/release/sdAI-release.apk
      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: sdAI-debug.apk
          path: app/build/outputs/apk/debug/sdAI-debug.apk

